### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [danielhenrymantilla/next-gen-rs#1]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/danielhenrymantilla/next-gen-rs/blob/dc0cf86921d4b34aebda36db850754746a7ce382/run_miri.sh#L11
In fact, Miri supports panics now, so a plain `cargo miri test` should just work. `cargo miri setup` is also not needed any more.

**Comment by danielhenrymantilla** [comment]
Gotcha, thanks for the info @RalfJung, will update accordingly
