### ISSUE TITLE
Support resume arguments

### ISSUE THREAD

**Issue by vorot93** [danielhenrymantilla/next-gen-rs#2]
I'm writing an [Ethereum Virtual Machine interpretation](https://github.com/vorot93/evmodin). It's basically an interpreter loop for bytecode that can interact with Ethereum blockchain. In order to decouple the two, the interpreter is written as a generator that yields with an interrupt, like _get data from database_ and can be resumed with data from database. This requires resume arguments - they are supported by `genawaiter` which I'm currently using, but it's not `#![no_std]` compatible. Support for resume arguments in `next-gen` would be nice to see as well!

**Comment by danielhenrymantilla** [comment]
Yeah, that's a sensible request; I may be able to look into it this week-end

**Comment by vorot93** [comment]
@danielhenrymantilla did you have a chance to look into this recently?

**Comment by danielhenrymantilla** [comment]
Yep; I have come acquainted with the code, updated it a bit (last commit was a bit old; no `cfg`-gated docs, for instance), and started implementing the resume arguments.

FWIW, I haven't totally settled with the syntax for interacting with the coroutine, so feel free to chime in. Here is what I'm currently leaning towards:

```rust
use ::next_gen::prelude::*;

fn main ()
{
    #[coroutine(yield(i32))]
    fn coro_fn (foo: char, mut resume_arg @ yield_: u8)
      -> &'static str
    {
        assert_eq!(foo, 'f');
        assert_eq!(resume_arg, 42);
        resume_arg = yield_!(1);
        assert_eq!(resume_arg, 27);
        return "baz";
    }

    mk_coroutine!(let mut coro = coro_fn('f'));

    let mut next = |arg: u8| coro.as_mut().resume_with(arg);

    match next(42) {
        | GeneratorState::Yield(yielded) => assert_eq!(yielded, 1),
        | GeneratorState::Return(_) => unreachable!(),
    }
    match next(27) {
        | GeneratorState::Yield(_) => unreachable!(),
        | GeneratorState::Return(returned) => assert_eq!(returned, "foo"),
    }
}
```

And I'm hesitating between `.resume_with(…)` and `.resume_arg(…)` or even `.next(…)`.

Also, the syntax with `arg @ yield_` may look weird, but it's technically valid rust (`var_name @ pattern`), and actually maps the coroutine abstraction very well: we only truly enter a coroutine body when resumed, and type-safety-wise, there is no distinction between the first resume and those which follow, so it makes sense to receive a resume argument right when starting.

**Comment by vorot93** [comment]
I think it makes sense to have universal `resume` [like in std](https://doc.rust-lang.org/stable/std/ops/trait.Generator.html).

Not sure about `arg @ yield_` syntax. I'd personally stick to native Generators in std nightly as close as possible, but ultimately it does not matter much.

**Comment by danielhenrymantilla** [comment]
Huh, did not see [that new version of `Generator`](https://doc.rust-lang.org/1.56.1/std/ops/trait.Generator.html). I strongly disagree with it being a generic parameter and not an associated type: I'm pretty sure they'll be using an associated type eventually. I also softly disagree with not distinguishing between a stateless-resume coroutine (a generator) and a stateful one. That is, in `nightly`, I'd write:

```rust
pub trait Generator = Coroutine<Resume = ()>;
```

On stable, and thus my crate, I'll write:

```rust
pub trait Generator:
    Coroutine<Resume = ()>
{}
impl<T : ?Sized> Generator for T
where Self:
    Coroutine<Resume = ()>,
{}
```

and use `.resume()` everywhere

**Comment by vorot93** [comment]
I'm not sure if having two separate `resume` methods is worth it when there's empty tuple type exactly for such occasions.

**Comment by danielhenrymantilla** [comment]
Yep, I had missed the fact the `Generator` trait had been updated since the last time I had checked it; I've been a bit surprised by it being an generic parameter rather than an associated type (or even a GAT), but it makes sense in terms of supporting "higher-order resume arguments", which, in Rust more than in any language, would make sense to have to allow borrowing from the caller in a visual perspective.

Thanks for pointing that out, @vorot93; I somehow assumed the official `Generator` trait definition not to have been updated / changed already to support resume arguments. This is very promising stuff 🙂
